# Generated by scripts/cli/build-packaging.sh -- do not edit by hand.
class Tempr < Formula
  desc "Sign in, chat, and run agentic coding tasks against your Tempr license from the terminal"
  homepage "https://temprhq.io"
  version "0.9.12"
  license :cannot_represent

  on_macos do
    on_arm do
      url "https://temprhq.io/cli/v0.9.12/tempr-0.9.12-osx-arm64.tar.gz"
      sha256 "4b0148ed8684d42f3d25d96b99c299de2803f503d9f1d8aa169f370865d75adf"
    end
    on_intel do
      url "https://temprhq.io/cli/v0.9.12/tempr-0.9.12-osx-x64.tar.gz"
      sha256 "e99882d2a8fcbb8194e34fe08c01b07e6ba6c12e1934b92619c707d831db38d2"
    end
  end

  on_linux do
    on_arm do
      url "https://temprhq.io/cli/v0.9.12/tempr-0.9.12-linux-arm64.tar.gz"
      sha256 "d53032902da99725f8eed68026fddcd771dbdd26fd150696be9c8990ca637814"
    end
    on_intel do
      url "https://temprhq.io/cli/v0.9.12/tempr-0.9.12-linux-x64.tar.gz"
      sha256 "bd5ee19b86e6eceec14eebdbbbd41f6203e3b05fd359c640ed2fc17b9cdd6979"
    end
  end

  def install
    bin.install "tempr"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tempr --version")
  end
end
