# Generated by scripts/cli/build-packaging.sh -- do not edit by hand.
class Tempr < Formula
  desc "Sign in, chat, and run agentic coding tasks against your Tempr license from the terminal"
  homepage "https://temprhq.io"
  version "0.9.14"
  license :cannot_represent

  on_macos do
    on_arm do
      url "https://temprhq.io/cli/v0.9.14/tempr-0.9.14-osx-arm64.tar.gz"
      sha256 "e6bb8e30392f5113365a6f6a1f6cc518da001024920317a695877b23f58618cc"
    end
    on_intel do
      url "https://temprhq.io/cli/v0.9.14/tempr-0.9.14-osx-x64.tar.gz"
      sha256 "cb5db257f58633195051af09d3bb8ff5de4471dad9773254c81df21f98ff9c60"
    end
  end

  on_linux do
    on_arm do
      url "https://temprhq.io/cli/v0.9.14/tempr-0.9.14-linux-arm64.tar.gz"
      sha256 "2d8fff458e07b0c01dc801348575e24b6912d929fd78c0cfdbd13a56860fbe62"
    end
    on_intel do
      url "https://temprhq.io/cli/v0.9.14/tempr-0.9.14-linux-x64.tar.gz"
      sha256 "a290543356852f7534a73786ee1585ee97196fc25e1258da02fd377ebf151013"
    end
  end

  def install
    bin.install "tempr"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tempr --version")
  end
end
